name: Build
on: [push, pull_request]
jobs:

  test:
    runs-on: ubuntu-latest
    container: nimlang/nim
    strategy:
      matrix:
        threads: [on, off]
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: nimble --threads:${{ matrix.threads }} test -y

  benchmark:
    runs-on: ubuntu-latest
    container: nimlang/nim
    steps:
    - uses: actions/checkout@v1
    - name: Benchmark
      run: nimble -y -d:release benchmark

  readme:
    runs-on: ubuntu-latest
    container: nimlang/nim
    steps:
    - uses: actions/checkout@v1
    - name: Build readme code
      run: nimble readme
