name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: nimlang/nim
    steps:
    - uses: actions/checkout@v1
    - name: Build project
      run: |
        nimble test -y
        nimble -y -d:release benchmark
