name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: nimlang/nim
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: nimble test -y
    - name: Benchmark
      run: nimble -y -d:release benchmark
    - name: Build readme code
      run: nimble readme
