name: Documentation Deploy
on:
  push:
    branches:
      - main
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iffy/install-nim@v5
        with:
          version: binary:2.0.10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: nimble install -y markdown
      - run: nimble documentation
      - name: Deploy documents
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ !env.ACT }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
