name: Documentation Deploy
on: [push]
jobs:
  docs:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    container: nimlang/nim
    steps:
    - uses: actions/checkout@v3
    - run: nimble install -y markdown
    - run: nimble documentation
    - run: cat docs/index.html
