name: Documentation Deploy
on:
  push:
    branches:
      - main
jobs:
  docs:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    container: nimlang/nim
    steps:
    - uses: actions/checkout@v3
    - run: nimble install -y markdown
    - run: nimble documentation
    - name: Deploy documents
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ !env.ACT }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
